### ISSUE TITLE
mirrorlist.centos.org is no more.

### ISSUE THREAD

**Issue by BeZazz** [AtlasGondal/centos7-eol-repo-fix#1]
I found an answer serverfault by mlazarov

sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/CentOS-*.repo
sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/CentOS-*.repo
sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/CentOS-*.repo

After running the above "centos7-eol-repo-fix " worked perfectly.

**Comment by AtlasGondal** [comment]
Thanks for pointing out, it is using the vault.centos.org.
